name: 'CI'
on: [push, pull_request]

jobs:
  ci:
    needs: [test, downstream]
  test:
    name: yarn ${{ matrix.yarncmd }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --pure-lockfile
      - name: Run Tests
        run: yarn test

  downstream:
    name: Test downstream ${{ matrix.group }} projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: ['angular', 'angularjs', 'react']
    steps:
      - uses: actions/checkout@v2
      - name: Prepare to Test Downstream Projects
        run: |
          npm config set scripts-prepend-node-path auto
          git config --global user.email uirouter@github.actions
          git config --global user.name uirouter_github_actions
      - name: Install Dependencies
        run: yarn install --pure-lockfile
      - name: Test Downstream Projects
        run: yarn test:downstream --group ${{ matrix.group }}
