name: 'CI'

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_OPTIONS: --openssl-legacy-provider

jobs:
  ci:
    needs: [test, downstream]
    runs-on: ubuntu-latest
    steps:
      - run: true
  test:
    name: npm test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Check Peer Dependencies
        run: npx check-peer-dependencies
      - name: Run Tests
        run: npm test

  downstream:
    name: Test downstream ${{ matrix.group }} projects
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: ['angular', 'angularjs', 'react']
    steps:
      - uses: actions/checkout@v2
      - name: Prepare to Test Downstream Projects
        run: |
          git config --global user.email uirouter@github.actions
          git config --global user.name uirouter_github_actions
      - name: Install Dependencies
        run: npm ci
      - name: Test Downstream Projects
        run: npm run test:downstream -- --group ${{ matrix.group }}
